### ISSUE TITLE
webgl-gl-error-check fails on ArrayBuffers passed to bufferData

### ISSUE THREAD

**Issue by bhouston** [greggman/webgl-helpers#1]
The code seems to make an assumption typed arrays are always passed in.

![Screenshot from 2020-07-18 13-13-00](https://user-images.githubusercontent.com/588541/87857928-878f9500-c8f8-11ea-8258-7faeea5bbbda.png)

Because it assumes src.buffer exists.  But on ArrayBuffer and ArrayBufferView it doesn't per the spec:

https://developer.mozilla.org/en-US/docs/Web/API/ArrayBufferView
https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/bufferData

**Comment by greggman** [comment]
Thanks for the report. Fixed.

Just FYI though. MDN is **NOT** the spec. MDN is a user edited wiki and is often wrong.

**Comment by bhouston** [comment]
thx!
