### ISSUE TITLE
webgl-show-draw-calls doesn't work - origFn should be fn?

### ISSUE THREAD

**Issue by bhouston** [greggman/webgl-helpers#2]
put it into a page via:
```
<script>
      (() => { const s = document.createElement('script'); s.src = 'https://greggman.github.io/webgl-helpers/webgl-show-draw-calls.js'; document.firstElementChild.appendChild(s) })();

    </script>
```

![Screenshot from 2020-07-18 13-22-24](https://user-images.githubusercontent.com/588541/87858153-dbe74480-c8f9-11ea-9bf1-2c99303af913.png)

**Comment by greggman** [comment]
strange that it ever worked. fixed.

FYI: that syntax is for pasting into the JavaScript console. Using a `<script>` tag you an just include it.

**Comment by bhouston** [comment]
thx you for the quick turnaround!
